name: CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
    ci:
        uses: OpenHPS/workflows/.github/workflows/monorepo.yml@v1
        secrets: inherit
        with:
            {}
